### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.Interceptor$Chain.readTimeoutMillis()I

### ISSUE THREAD

**Issue by tiny-cababge** [rickfast/consul-client#326]
When ever i tried to register, i get this error. 
Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.Interceptor$Chain.readTimeoutMillis()I
	at com.orbitz.consul.cache.TimeoutInterceptor.intercept(TimeoutInterceptor.java:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at com.orbitz.consul.AgentClient.ping(AgentClient.java:61)
	at com.orbitz.consul.Consul$Builder.build(Consul.java:617)
	at Application.main(Application.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

`      Consul consul = Consul.builder().build(); // connect to Consul on localhost
        AgentClient agentClient = consul.agentClient();

        String serviceName = "MyService";
        String serviceId = "MyService-Peter1";

        
        agentClient.register(8080, 3L, serviceName, serviceId); // registers with a TTL of 3 seconds
        try {
            agentClient.pass(serviceId);
        } catch (NotRegisteredException e) {
            System.out.println("peter " + e);
        }
`

**Comment by yfouquet** [comment]
Hi @tiny-cababge,

Can you please give us more details?
 - the version of the consul-client library
 - the classifier of the consul-client library (if any)
 - the version(s) of okhttp in your dependency tree.

It looks like you are not using (at runtime) the same version of okhttp.
Note that:
 - withReadTimeout() was introduced in okhttp in July 2017: https://github.com/square/okhttp/pull/3432
This means that it is available in okhttp >= 3.9.0.
 - consul-client uses [Okhttp 3.9.0](https://github.com/rickfast/consul-client/blob/master/pom.xml#L44) 
 - the dependency on okhttp3 is relocated in the [shaded artifact](https://github.com/rickfast/consul-client/blob/master/pom.xml#L298)

**Comment by yfouquet** [comment]
I cannot tell you without without knowing what you use. Which version of consul-client do you use? Do you use the shaded artifact? Is there any other version on okhttp in your dependency tree?

Seeing the exception (NoSuchMethodError), you found the class, so you had a okhttp in your classpath. My guess is that an older version of okhttp was used (maybe because of other dependencies) and you got a dependency conflict. You should find out the reason as your fix may add new issues. Note that the shaded version protects you from such conflicts.

**Comment by tiny-cababge** [comment]
So i think the package uploaded to maven central is wrong, but ive just not got round to checking it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
