### ISSUE TITLE
okhttp3 version need upgrade to Use OkHttp 3.12.2 or newer.

### ISSUE THREAD

**Issue by jiancaiHub** [rickfast/consul-client#388]
According to example build a acl `Consul `, but it failed to run
issus  
```
Caused by: java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458) ~[retrofit-2.5.0.jar:?]
	at com.orbitz.consul.Consul$Builder.createRetrofit(Consul.java:789) ~[consul-client-1.3.6.jar:?]
	at com.orbitz.consul.Consul$Builder.build(Consul.java:682) ~[consul-client-1.3.6.jar:?]
```
then find this :
> https://github.com/square/retrofit/issues/3058

I think `consul-client` need to upgrade okhttp3's version.

**Comment by rickfast** [comment]
fixed in 1.3.7
