### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by ttj4** [rickfast/consul-client#404]
I am working on a grpc project using consul. With grpc-protobuf there is a guava dependency com.google.guava:guava [version:26.0-android] and with consul com.google.guava:guava [version:22.0].

Since maven automatically links grpc dependency of guava and throws the following error

`java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsed()Ljava/time/Duration;
	at com.orbitz.consul.cache.ConsulCache$1.onComplete(ConsulCache.java:123)
	at com.orbitz.consul.util.Http$1.onResponse(Http.java:79)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by cricket007** [comment]
Latest guava is 27-1 : https://github.com/rickfast/consul-client/blob/master/pom.xml#L37

**Comment by rickfast** [comment]
what @cricket007 (thanks!) said. closing
