### ISSUE TITLE
How can there be so many compile problems

### ISSUE THREAD

**Issue by GreedyPirate** [rickfast/consul-client#406]
In consul-client pom.xml, this dependency use provided scope, it not reasonable
```
        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>value</artifactId>
            <version>${immutables.version}</version>
            <scope>provided</scope>
        </dependency>
```
so I add this to my project, it works
```
        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>value</artifactId>
            <version>2.7.5</version>
        </dependency>
```

then I find so many issue about NoSuchMethodError
```
Caused by: java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458) ~[retrofit-2.5.0.jar:na]
	at com.orbitz.consul.Consul$Builder.createRetrofit(Consul.java:812) ~[consul-client-1.4.0.jar:na]
	at com.orbitz.consul.Consul$Builder.build(Consul.java:705) ~[consul-client-1.4.0.jar:na]
```

for this one， I add
```
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>${okhttp.version}</version>
        </dependency>
```

another issue happens
```
Caused by: java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
	at okio.Segment.writeTo(Segment.kt:164) ~[okio-2.4.1.jar:na]
	at okio.Segment.compact(Segment.kt:147) ~[okio-2.4.1.jar:na]
	at okio.Buffer.write(Buffer.kt:1849) ~[okio-2.4.1.jar:na]
	at okio.Buffer.read(Buffer.kt:1860) ~[okio-2.4.1.jar:na]
	at okio.Buffer.writeAll(Buffer.kt:1650) ~[okio-2.4.1.jar:na]
	at okio.Options$Companion.buildTrieRecursive(Options.kt:187) ~[okio-2.4.1.jar:na]
	at okio.Options$Companion.buildTrieRecursive(Options.kt:174) ~[okio-2.4.1.jar:na]
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113) ~[okio-2.4.1.jar:na]
	at okio.Options$Companion.of(Options.kt:72) ~[okio-2.4.1.jar:na]
	at okhttp3.internal.Util.<clinit>(Util.kt:68) ~[okhttp-4.3.1.jar:na]
	at com.orbitz.consul.Consul$Builder.build(Consul.java:686) ~[consul-client-1.4.0.jar:na]
```

same solution
```
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.3.61</version>
        </dependency>
```

all problems start here： Consul$Builder.build， so just fix it quickly

**Comment by cricket007** [comment]
immutables is an annotation-processor, it should therefore only be compiled. 

https://immutables.github.io/getstarted.html

**Comment by rickfast** [comment]
"so just fix it quickly". 

try again. maybe tell me what you're trying to do. if you're trying to develop against this repo, then read the readme. if you're trying to link this project, and you're seeing NoSuchMethodExceptions, you likely have conflicting dependencies.

**Comment by GreedyPirate** [comment]
my solution is right，and it works，I hope people who have the same problems can see

**Comment by cricket007** [comment]
Happy it works for you, but it also works for me without chasing external dependencies.

Make sure you bundle an uber jar when you run the code
