### ISSUE TITLE
AgentClient.getAgent() fails with Consul 1.8.4 and later

### ISSUE THREAD

**Issue by dnault** [rickfast/consul-client#437]
To reproduce the issue, run Consul 1.8.4 or later on localhost and default port, and then:

    Consul consul = Consul.builder().build();
    System.out.println(consul.agentClient().getAgent());

This fails with an exception whose root cause is:

    Caused by: java.lang.IllegalStateException: Cannot build DebugConfig, some of required attributes are not set [logLevel, enableSyslog]
        at com.orbitz.consul.model.agent.ImmutableDebugConfig$Builder.build(ImmutableDebugConfig.java:2121)
        at com.orbitz.consul.model.agent.ImmutableDebugConfig.fromJson(ImmutableDebugConfig.java:1586)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

In 1.8.4, the structure of the `/v1/agent/self` HTTP response changed; the `LogLevel` and `EnableSyslog` fields are now nested under a new `Logging` node.

Before 1.8.4:

    {
      "DebugConfig": {
        "LogLevel": "DEBUG",
        "EnableSyslog": false,
        ...
      },
      ...
    }

1.8.4 and later:

    {
      "DebugConfig": {
        "Logging": {
          "LogLevel": "DEBUG",
          "EnableSyslog": false,
          ...
        },
        ...
      }
      ...
    }

**Comment by dnault** [comment]
According to the [Consul documentation for this endpoint](https://www.consul.io/api-docs/agent#read-configuration) (emphasis added):

> This endpoint returns the configuration and member information of the local agent. The Config element contains a subset of the configuration and its format will not change in a backwards incompatible way between releases. DebugConfig contains the full runtime configuration but ***its format is subject to change without notice or deprecation.***

Instead of exposing the DebugConfig as a POJO in the Consul client API, perhaps it would be less brittle to expose this information as a Map<String,Object> or some other way that doesn't depend on the structure of the JSON response.

**Comment by dnault** [comment]
Duplicate of #431
